version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: my_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_crawler
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: on-failure

volumes:
  pgdata:
